Repository KSP-KOS/KOS, pull requests merged in 2020-08, with the labels that each got.

#2690 Add :ETA suffix to OrbitInfo
  src/kOS/Binding/FlightStats.cs
  src/kOS/Suffixed/OrbitEta.cs
  src/kOS/Suffixed/OrbitInfo.cs
  src/kOS/Suffixed/VesselEta.cs
  src/kOS/kOS.csproj
Labels: Pending Documentation

#2689 Make createorbit() take mean anomaly at epoch in degrees
  src/kOS/Function/Suffixed.cs
Labels: Breaking, enhancement

#2731 Manually typed what was in PR #2707 because it was hard to merge.
  doc/source/contents.rst
  doc/source/general/volumes.rst
  doc/source/getting_help.rst
Labels: documentation
